### ISSUE TITLE
Graphics guidelines

### ISSUE THREAD

**Issue by peteroupc** [lospec/lospec-rpg#3]
I have written [suggestions on graphics guidelines](https://peteroupc.github.io/graphics.html) that games with a classic look can choose to follow.

If this game is intended to be 2-D only, the guidelines include the following:

- Up to four tile-based 2D layers can be displayed at a time.
- There are sixteen palettes of 16 colors each.
- Each tile is 8 × 8 pixels and uses the colors of one of the sixteen palettes just described.
- The layers may contain transparent pixels.
- Separate from layers, 2D sprites can be displayed. No more than 128 sprites may be displayed at a time. Each sprite is up to 64 &times; 64 pixels. Sprites may contain transparent pixels.

The guidelines above are for a 256 × 192 screen resolution.  For other resolutions, the maximum texture size, sprite count, and sprite size will change in proportion.

**Comment by skeddles** [comment]
![i-know-more-than-you-i-know-you](https://github.com/user-attachments/assets/c6f70bf8-2e33-41f5-a912-6458842e3563)

**Comment by peteroupc** [comment]
What was wrong with my suggestions here?  Closing this issue with a text reason would have been more helpful to me than closing it with an opaque image and nothing else.  I was hoping that some discussion could occur on technical aspects of the graphics that are appropriate for this project, beyond the fact that it should be pixel art.

**Comment by HumanInTheory** [comment]
Sorry, project admin thought you were a bot.

This project is themed off of a channel in our Discord server, so we weren't really anticipating anybody outside of our community interacting with it beyond playing the game. We already have the palette picked (we are a palette community after all), along with most of the graphics specifications.

Screen size: 240x160
Palette: https://lospec.com/palette-list/lospec-emoji
Sprite size: 32x32
Tile size: 16x16

**Comment by peteroupc** [comment]
I see; then those specifications should be made clear in the README.  Given those specifications I have little further to suggest; perhaps the sprite limit of 128 simultaneous sprites will come naturally, for example.

~~@skeddles : I hope you will resolve this misunderstanding, including on this issue page.~~

That is all for now.

**Comment by skeddles** [comment]
Ha, so sorry, I really thought you were a bot because it seemed a but unrelated to what we established so far (as @HumanInTheory mentioned).

I will add more information to the README about this soon, though it's still very early so nothing is set in stone. We're also basing it off sprites we created for a web comic, so the style is pretty well established.

**Comment by peteroupc** [comment]
Thank you for responding.  That is all.

**Comment by skeddles** [comment]
added graphics guidelines to readme
